server:
  port: 9003
  
  
spring.datasource.url: jdbc:postgresql://postgres:5432/services
spring.datasource.username: postgres
spring.datasource.password: root

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size: 10
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

#eureka:
 # client:
  #  register-with-eureka:  true
   # fetch-registry: true
    #service-url:     # defaultZone: http://localhost:8761/eureka/
   # instance:
    #  hostname: localhost
    
springfox:
  documentation:
    auto-startup: false